In [1]:
from visuals import *
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 50)

Single property

In [2]:
sdate = np.datetime64('2018-09-30')
bcap = 0.08
scap = 0.065
emonth = 7
fyrrent = 35e6
rentinc = 0.
incperiod = 1.
ltv = 0.6
lfee = 1e-2
r0 = 2.5e-2
libor = (np.linspace(0, 10, 11)*0.05 + np.ones(11)*1.95)/100.
acost = 1e-2
ecost = 5e-2
fyroexp = 0.
oexpinc = 0.
aperiod = np.inf
aintrate = 0.
repprem = 1.
cf = singlepropcf(sdate, bcap, scap, emonth, fyrrent, rentinc, incperiod, ltv, lfee, r0, libor, acost, ecost, fyroexp, oexpinc, aperiod, aintrate, repprem)

262500000.0


In [3]:
viewsinglecf(*cf)

Month #                            0                1                2  \
Dates                     2018-09-30       2018-10-31       2018-11-30   
Starting debt                  $0.00  $262,500,000.00  $262,500,000.00   
Loan                 $259,875,000.00            $0.00            $0.00   
Property buy/sell   -$441,875,000.00            $0.00            $0.00   
Rent                           $0.00    $2,916,666.67    $2,916,666.67   
Operating expenses            -$0.00           -$0.00           -$0.00   
Interest                      -$0.00   -$1,017,187.50     -$995,312.50   
Amortization                  -$0.00            $0.00            $0.00   
Final debt           $262,500,000.00  $262,500,000.00  $262,500,000.00   
Total cash flow     -$182,000,000.00    $1,899,479.17    $1,921,354.17   

Month #                           3                4                5  \
Dates                    2018-12-31       2019-01-31       2019-02-28   
Starting debt       $262,500,000.00  $262,500,000.00  $262,500,000.00   
Loan                          $0.00            $0.00            $0.00   
Property buy/sell             $0.00            $0.00            $0.00   
Rent                  $2,916,666.67    $2,916,666.67    $2,916,666.67   
Operating expenses           -$0.00           -$0.00           -$0.00   
Interest             -$1,039,791.67   -$1,051,093.75     -$959,583.33   
Amortization                  $0.00            $0.00            $0.00   
Final debt          $262,500,000.00  $262,500,000.00  $262,500,000.00   
Total cash flow       $1,876,875.00    $1,865,572.92    $1,957,083.33   

Month #                           6                 7  
Dates                    2019-03-31        2019-04-30  
Starting debt       $262,500,000.00   $262,500,000.00  
Loan                          $0.00  -$262,500,000.00  
Property buy/sell             $0.00   $511,538,461.54  
Rent                  $2,916,666.67             $0.00  
Operating expenses           -$0.00            -$0.00  
Interest             -$1,073,697.92    -$1,050,000.00  
Amortization                  $0.00             $0.00  
Final debt          $262,500,000.00             $0.00  
Total cash flow       $1,842,968.75   $247,988,461.54

In [4]:
ret = returns(cf[-1], cf[0])
viewret(*ret)

Returns            Value
Inflow   $259,351,794.87
Outflow  $182,000,000.00
Profit    $77,351,794.87
MOIC             1.42501
IRR             0.868289

Portfolio modelling

In [5]:
sdate = np.datetime64('2018-09-30')
bcaps = np.ones(4)*0.08
scaps = np.ones(4)*0.065
emonths = [4, 5, 6, 7]
fyrrents = np.ones(4)*35e6/4.
rentincs = np.zeros(4)
incperiods = np.ones(4)
ltvs = np.ones(4)*0.6
lfee = 0.01
r0 = 0.025
libor = (np.linspace(0, 10, 11)*0.05 + np.ones(11)*1.95)/100.
acosts = np.ones(4)*1e-2
ecosts = np.ones(4)*5e-2
fyroexps = np.zeros(4)
oexpincs = np.zeros(4)
aperiod = np.inf
aintrate = 0.
repprem = 1.2
alldates, amort, allcf, debt, totcf = portcf(sdate, bcaps, scaps, emonths, fyrrents, rentincs, incperiods, ltvs, lfee, r0, libor, acosts, ecosts, fyroexps, oexpincs, aperiod, aintrate, repprem)

262500000.0
78750000.0
78750000.0
78750000.0
78750000.0


In [6]:
names = ['Bicentenario', 'Santa Laura', 'Monumental', 'San Carlos']
viewportcf(names, alldates, amort, allcf, debt, totcf)

Month #                         0                1                2  \
Dates                  2018-09-30       2018-10-31       2018-11-30   
Starting debt               $0.00  $262,500,000.00  $262,500,000.00   
Amortization                $0.00            $0.00            $0.00   
Bicentenario      -$45,500,000.00      $474,869.79      $480,338.54   
Santa Laura       -$45,500,000.00      $474,869.79      $480,338.54   
Monumental        -$45,500,000.00      $474,869.79      $480,338.54   
San Carlos        -$45,500,000.00      $474,869.79      $480,338.54   
Final debt        $262,500,000.00  $262,500,000.00  $262,500,000.00   
Total cash flow  -$182,000,000.00    $1,899,479.17    $1,921,354.17   

Month #                        3                4                5  \
Dates                 2018-12-31       2019-01-31       2019-02-28   
Starting debt    $262,500,000.00  $183,750,000.00  $105,000,000.00   
Amortization               $0.00            $0.00            $0.00   
Bicentenario         $469,218.75   $48,871,841.95            $0.00   
Santa Laura          $469,218.75      $466,393.23   $48,894,719.55   
Monumental           $469,218.75      $466,393.23      $489,270.83   
San Carlos           $469,218.75      $466,393.23      $489,270.83   
Final debt       $183,750,000.00  $105,000,000.00   $26,250,000.00   
Total cash flow    $1,876,875.00   $50,271,021.63   $49,873,261.22   

Month #                       6                7  
Dates                2019-03-31       2019-04-30  
Starting debt    $26,250,000.00            $0.00  
Amortization              $0.00            $0.00  
Bicentenario              $0.00            $0.00  
Santa Laura               $0.00            $0.00  
Monumental       $48,866,190.91            $0.00  
San Carlos          $460,742.19  $101,372,115.38  
Final debt                $0.00            $0.00  
Total cash flow  $49,326,933.09  $101,372,115.38

In [7]:
viewret(*returns(totcf, alldates))

Returns            Value
Inflow   $256,541,039.66
Outflow  $182,000,000.00
Profit    $74,541,039.66
MOIC             1.40957
IRR              1.07132

Libor

In [1]:
libf = pd.read_excel('blc08-10.xlsx', 'fwd curve') 

NameError: name 'pd' is not defined

In [502]:
data

Open     High      Low   Close     Volume  ExDividend  \
Date                                                                 
2018-03-27  18.72  19.0605  18.4200  19.000   463723.0        0.00   
2018-03-26  18.60  18.7200  18.3900  18.710   418747.0        0.00   
2018-03-23  18.83  18.8700  18.2900  18.410   573727.0        0.00   
2018-03-22  18.74  19.1900  18.6800  18.810   568974.0        0.00   
2018-03-21  18.90  18.9300  18.6700  18.850   285040.0        0.00   
2018-03-20  19.02  19.1000  18.6600  18.890   355499.0        0.00   
2018-03-19  19.08  19.1350  18.8700  19.040   355169.0        0.00   
2018-03-16  19.11  19.1900  18.9550  19.180   525264.0        0.00   
2018-03-15  19.23  19.3200  18.9200  19.090   307732.0        0.00   
2018-03-14  19.10  19.2900  19.0800  19.220   297349.0        0.00   
2018-03-13  19.10  19.2200  18.9700  19.050   284979.0        0.00   
2018-03-12  18.96  19.1300  18.9000  19.020   329159.0        0.00   
2018-03-09  19.01  19.0285  18.7542  18.960   311081.0        0.00   
2018-03-08  19.16  19.2700  18.7900  18.960   478452.0        0.00   
2018-03-07  18.49  19.1900  18.4900  19.150   481492.0        0.00   
2018-03-06  18.58  18.6300  18.2200  18.520   415095.0        0.00   
2018-03-05  18.36  18.7000  18.3600  18.570   354276.0        0.00   
2018-03-02  18.13  18.4600  17.9000  18.420   435628.0        0.00   
2018-03-01  18.17  18.4500  17.9500  18.190   394442.0        0.00   
2018-02-28  18.45  18.6480  18.1200  18.170   464148.0        0.00   
2018-02-27  18.94  19.0000  18.4100  18.410   828900.0        0.00   
2018-02-26  19.25  19.2650  18.7200  18.900   696709.0        0.00   
2018-02-23  19.33  19.3600  19.0900  19.260   657174.0        0.00   
2018-02-22  19.35  19.4500  19.1200  19.200   551969.0        0.00   
2018-02-21  19.60  19.7399  19.2400  19.250   495381.0        0.00   
2018-02-20  20.30  20.6400  19.6200  19.700   546778.0        0.00   
2018-02-16  20.29  20.9600  19.9950  20.340   386759.0        0.00   
2018-02-15  20.09  20.3800  20.0400  20.310   348685.0        0.00   
2018-02-14  19.91  20.1200  19.6200  20.040   422159.0        0.00   
2018-02-13  20.00  20.1900  19.7998  20.110   389109.0        0.00   
2018-02-12  20.45  20.4500  19.4100  20.110   521331.0        0.00   
2018-02-09  20.08  20.5500  19.8500  20.400   372790.0        0.00   
2018-02-08  20.64  20.7350  19.9600  19.970   323530.0        0.00   
2018-02-07  20.81  21.2000  20.6200  20.680   320492.0        0.00   
2018-02-06  20.52  21.2000  20.2201  20.810   411920.0        0.00   
2018-02-05  21.64  21.6600  20.7100  20.745   316033.0        0.00   
2018-02-02  21.76  21.8900  21.5100  21.700   325579.0        0.00   
2018-02-01  22.36  22.5200  21.8500  21.895   256382.0        0.00   
2018-01-31  22.15  22.3600  22.0000  22.355   382371.0        0.00   
2018-01-30  22.30  22.3900  22.0700  22.080   276908.0        0.00   
2018-01-29  22.63  22.8600  22.2900  22.370   326729.0        0.00   
2018-01-26  22.89  22.8900  22.6000  22.700   474347.0        0.00   
2018-01-25  23.73  23.7300  23.3100  23.360   454080.0        0.00   
2018-01-24  23.61  23.7500  23.5300  23.670   350039.0        0.00   
2018-01-23  23.40  23.7600  23.2400  23.630   365042.0        0.00   
2018-01-22  23.09  23.3900  23.0000  23.380   278047.0        0.00   
2018-01-19  22.78  23.0800  22.7200  23.080   233308.0        0.00   
2018-01-18  23.24  23.2400  22.7100  22.750   323777.0        0.00   
2018-01-17  23.14  23.3100  22.9700  23.290   270854.0        0.00   
2018-01-16  23.30  23.4901  23.0200  23.020   320742.0        0.00   
2018-01-12  23.45  23.4600  23.0700  23.080   287062.0        0.00   
2018-01-11  23.24  23.5700  23.2400  23.450   395444.0        0.00   
2018-01-10  23.70  23.7500  23.1700  23.210   681756.0        0.00   
2018-01-09  24.20  24.2600  23.7600  23.780   296904.0        0.00   
2018-01-08  24.05  24.2800  23.9316  24.220   161095.0        0.00   
2018-01-05  24.16  24.2

In [2]:
sdate = 
bcap =
scap =
emonth

-88848.78867834169

In [5]:
amortcf(1e6, 0.01, np.zeros(12), 12)*12

array([    0.        , 88848.78867834, 88848.78867834, 88848.78867834,
       88848.78867834, 88848.78867834, 88848.78867834, 88848.78867834,
       88848.78867834, 88848.78867834, 88848.78867834, 88848.78867834])

In [7]:
intrate = np.abs(np.random.randn(12))*2
intrate

array([0.77375512, 0.36964537, 0.42931581, 0.99750529, 0.39859078,
       0.90663952, 2.58550755, 0.17754375, 0.56298883, 2.48422065,
       0.22999129, 0.63216402])

In [13]:
np.pmt(0, np.inf, 1e6)

-0.0

In [10]:
np.linspace(1, 9, 9)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
a = np.linspace(1, 9, 9)
np.roll(a, -1)

array([2., 3., 4., 5., 6., 7., 8., 9., 1.])

In [3]:
np.linspace(0, 10, 11)*0.05 + np.ones(11)*1.95

array([1.95, 2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45])

In [13]:
a = np.ones(10)
a[0] = 0
a[5:10] = 0

In [15]:
np.where(a == 0)[2:]

(array([0, 5, 6, 7, 8, 9], dtype=int64),)

In [12]:
a

array([0., 0., 0., 0., 0., 2., 2., 2., 2., 2.])